#!/bin/bash
echo $'<!DOCTYPE html>\n\
<html lang="en">\n\
  <head>\n\
    <title>NGINX</title>\n\
	<style>.rcorners { border-radius: 25px; background: lightgray; width: 500px; margin: 80px auto 0 auto; padding:75px 100px 75px 100px; height: 150px; }\n\
	h1,p {font-family:Arial, Helvetica, sans-serif;}</style>\n\
  </head>\n\
  <body>\n\
      <div class="rcorners">\n\
        <h1>centos-nginx</h1><p>Congratulations, you\'ve successfully deployed the camw/centos-nginx image as container $HOSTNAME.</p>\n\
      </div>\n\
  </body>\n\
</html>'\
>> /usr/share/nginx/html/index.htm